FROM python:3.12.0-alpine3.18

WORKDIR /app

RUN pip install flask

# Copy the application code
COPY . .

# Set environment variables
#ENV POSTGRES_URL=db-url

# Expose the port
EXPOSE 9090

# Command to run the application
CMD ["python", "app.py"]

