apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ahmadaamir/project-microservice-frontend:db380bcc085f74bf4ea8b3161760ca3974c5e35d
        ports:
        - containerPort: 3000
        env:
        - name: DOCTORS_SERVICE_URL
          value: "doctors-service:9090"  # Update with the correct service name
        - name: APPOINTMENTS_SERVICE_URL
          value: "appointments-service:7070"  # Update with the correct service name
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30195
  type: NodePort
