version: '3'

services:

  appointments:
    image: ahmadaamir/project-microservice-appointments:0020174a95b0e7677e3134f4459a1216a5f87c8f 
    expose:
      - "7070"
    networks:
      - frontend_network

  doctors:
    image: ahmadaamir/project-microservice-doctors:0020174a95b0e7677e3134f4459a1216a5f87c8f 
    expose:
      - "9090"
    networks:
      - frontend_network

  frontend:
    image: ahmadaamir/project-microservice-frontend:9e8604a75b4675f92cc5161e8232aeb29074f8bf 
    ports:
      - "3000:3000"
    environment:
      DOCTORS_SERVICE_URL: doctors:9090
      APPOINTMENTS_SERVICE_URL: appointments:7070
    depends_on:
      - appointments
      - doctors
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
